// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndradeR_ClinicaVeterinaria_EvaluaciónProgreso1.Migrations
{
    [DbContext(typeof(AndradeR_SQL))]
    [Migration("20250501162245_RodrigoAndrade3")]
    partial class RodrigoAndrade3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AndradeR_ClinicaVeterinaria_EvaluaciónProgreso1.Models.DueñoMascota", b =>
                {
                    b.Property<int>("DueñoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DueñoId"));

                    b.Property<bool>("EsClienteFrecuente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("SaldoPendiente")
                        .HasColumnType("real");

                    b.HasKey("DueñoId");

                    b.ToTable("DueñoMascota");
                });

            modelBuilder.Entity("AndradeR_ClinicaVeterinaria_EvaluaciónProgreso1.Models.Mascota", b =>
                {
                    b.Property<int>("MascotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MascotaId"));

                    b.Property<int>("DueñoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("MascotaId");

                    b.HasIndex("DueñoId");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("AndradeR_ClinicaVeterinaria_EvaluaciónProgreso1.Models.VisitaVeterinaria", b =>
                {
                    b.Property<int>("VisitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitaId"));

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<int>("Motivo")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereMedicación")
                        .HasColumnType("bit");

                    b.HasKey("VisitaId");

                    b.ToTable("VisitaVeterinaria");
                });

            modelBuilder.Entity("AndradeR_ClinicaVeterinaria_EvaluaciónProgreso1.Models.Mascota", b =>
                {
                    b.HasOne("AndradeR_ClinicaVeterinaria_EvaluaciónProgreso1.Models.DueñoMascota", "DueñoMascota")
                        .WithMany()
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DueñoMascota");
                });
#pragma warning restore 612, 618
        }
    }
}
